#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : httpretty
Version  : 0.8.14
Release  : 54
URL      : http://pypi.debian.net/httpretty/httpretty-0.8.14.tar.gz
Source0  : http://pypi.debian.net/httpretty/httpretty-0.8.14.tar.gz
Summary  : HTTP client mock for Python
Group    : Development/Tools
License  : MIT
Requires: httpretty-license = %{version}-%{release}
Requires: httpretty-python = %{version}-%{release}
Requires: httpretty-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : certifi-python
BuildRequires : coverage-python
BuildRequires : httplib2
BuildRequires : nose-python
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-mock
BuildRequires : requests-python
BuildRequires : six
BuildRequires : six-python
BuildRequires : sure-python
BuildRequires : tornado-python
BuildRequires : tox
BuildRequires : urllib3-python
BuildRequires : virtualenv
Patch1: test.patch

%description
===============

%package license
Summary: license components for the httpretty package.
Group: Default

%description license
license components for the httpretty package.


%package python
Summary: python components for the httpretty package.
Group: Default
Requires: httpretty-python3 = %{version}-%{release}

%description python
python components for the httpretty package.


%package python3
Summary: python3 components for the httpretty package.
Group: Default
Requires: python3-core
Provides: pypi(httpretty)

%description python3
python3 components for the httpretty package.


%prep
%setup -q -n httpretty-0.8.14
cd %{_builddir}/httpretty-0.8.14
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602133473
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/httpretty
cp %{_builddir}/httpretty-0.8.14/COPYING %{buildroot}/usr/share/package-licenses/httpretty/698ca4029398a85256bbbf03bd1f116feb3382ed
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/httpretty/698ca4029398a85256bbbf03bd1f116feb3382ed

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
